default_config:

frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate

automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
group: !include groups.yaml

# sun2
sun2:
  - unique_id: my_home
    location: Nashville
    latitude: 36.1627
    longitude: -86.7816
    time_zone: America/Chicago
    observer_elevation: 0
    
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1

device_tracker:
  - platform: luci
    host: 192.168.8.1
    username: root
    password: !secret router_admin_password
    interval_seconds: 10
    consider_home: 180
    new_device_defaults:
      track_new_devices: true

# Split configs
counter: !include helpers/counters.yaml
timer: !include helpers/timers.yaml
input_text: !include helpers/input_text.yaml
input_boolean: !include helpers/input_boolean.yaml
# switch: !include switches/groups.yaml
template: !include templates/sensors.yaml
command_line: !include command_line.yaml
