- alias: "Turn on lights at golden hour when home"
  description: "Turns on lights at the beginning of golden hour if Caleb is home"
  trigger:
    - platform: state
      entity_id: sensor.golden_hour_active
      to: "True"
  condition:
    - condition: state
      entity_id: binary_sensor.caleb_presence
      state: "home"
    - condition: time
      after: '12:00:00'
      before: '23:00:00'
  action:
    - service: light.turn_on
      target:
        entity_id: 
          - light.above_range_lights
          - light.above_refrigerator_lights
          - light.entry_lamp 

      # Optional: Add brightness/color settings
      # data:
      #   brightness_pct: 80
      #   color_temp: 2700
  mode: single
