- alias: "Turn off everything except essentials (Night Plug-In or 2 AM)"
  description: "Turns off non-essentials when I plug in phone at night or at 2 AM daily"
  trigger:
    - platform: state
      entity_id: sensor.pixel_10_pro_battery_state
      to: "charging"
    - platform: state
      entity_id: sensor.pixel_10_pro_charger_type
      from: "none"
    - platform: time
      at: "02:00:00"

  condition:
    - condition: time
      after: "21:30:00"
      before: "06:00:00"
    - condition: state
      entity_id: sensor.caleb_presence
      state: "home"

  action:
    - service: homeassistant.turn_off
      data:
        entity_id: >
          {% set ignore = [
              'switch.nightstand_fan',
              'switch.q5_max_do_not_disturb',
              'switch.q5_max_dock_child_lock',
              'switch.front_camera_notifications',
              'switch.front_camera_motion_detection',
              'switch.front_camera_power',
              'switch.rear_camera_notifications',
              'switch.rear_camera_motion_detection',
              'switch.rear_camera_power'
          ] %}
          {% set all_entities = states.light | list + states.switch | list %}
          {{ expand(all_entities)
             | rejectattr('entity_id', 'in', ignore)
             | map(attribute='entity_id')
             | list }}
    - service: switch.turn_on
      target:
        entity_id:
          - switch.nightstand_fan
    - service: notify.mobile_app_pixel_10_pro
      data:
        title: "Power Down Complete"
        message: "All non-essential devices have been turned off"

  mode: single
