- alias: "Morning wake-up lights when unplugging phone"
  description: "Turn on morning lights when I unplug phone during the morning/day while home"
  trigger:
    - platform: state
      entity_id: sensor.pixel_10_pro_battery_state
      to: "discharging"
    - platform: state
      entity_id: sensor.pixel_10_pro_charger_type
      to: "none"

  condition:
    - condition: time
      after: "06:00:00"
      before: "18:00:00"
    - condition: state
      entity_id: sensor.caleb_presence
      state: "home"

  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.lava_lamp
          - light.giant_lava_lamp
    - service: switch.turn_off
      target:
        entity_id:
          - switch.nightstand_fan
  mode: single
